### ISSUE TITLE
Too long tag names make the pop-up scrollable

### ISSUE THREAD

**Issue by rene-coty** [david-swift/Flashcards#8]
### Describe the bug

When there is a long tag name, it will be displayed with scrollbars in the appearing pop-up instead of being cleanly cut-off, which spoils the aesthetics of the app (and makes navigating through tags a bit unpleasant)

### To Reproduce

1. Create a long Tag name (e.g. something in French 😇)
2. Click the Tag button next to a FlashCard
3. Tag name is partially hidden, with scrollbars appearing

### Expected behavior

I don't really expect the pop-up to exactly fit the size of the tag (it could be too long), but a more clean solution would be to make it a bit adaptive, with a maximum size beyond which the words are simply cut with '…'

### Additional context

![Capture d’écran du 2024-02-25 19-31-32](https://github.com/david-swift/Flashcards/assets/95506494/e1bf53d2-d1c2-4701-b185-6d54c5155ccf)

**Comment by david-swift** [comment]
I fixed it in the commit 9fc0ab1.
![Screenshot from 2024-02-26 06-14-02](https://github.com/david-swift/Flashcards/assets/106754840/42caad7f-b9ff-4edb-9548-443c7a828802)
![Screenshot from 2024-02-26 06-14-17](https://github.com/david-swift/Flashcards/assets/106754840/5cb4ac68-c8a0-46b3-abcf-3fbacefaf5e9)
![Screenshot from 2024-02-26 06-15-08](https://github.com/david-swift/Flashcards/assets/106754840/ef586215-1eb5-48cc-bc14-b28ea7350265)

The popup's size is static and does not expand at all, as this would be difficult to implement with the [FlowBox](https://docs.gtk.org/gtk4/class.FlowBox.html) (which holds the tags) that seems to always take up the maximum width. I dont think expanding would enhance the usability very much, so I did not implement it. Removing the scroll view does make it look much more appealing, thanks!
