### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by rene-coty** [david-swift/Flashcards#9]
### Describe the bug

Each time the app is reopened it will default to a fixed size, which is not always convenient

### To Reproduce

1. Adjust the window to a custom size
2. Quit
3. Re-open

### Expected behavior

I would expect the app to remember its last size. Otherwise it can be frustrating when you have long Sets names which will end up being cut-off everytime you restart the app (see screenshot below)

### Additional context

![Capture d’écran du 2024-02-25 19-51-44](https://github.com/david-swift/Flashcards/assets/95506494/bfabd4b1-59d5-4aaf-acc0-4ca318f18f9c)

**Comment by rene-coty** [comment]
Btw I hope you don't mind me pointing out all these little papercuts 😇, I really appreciate your work!

**Comment by david-swift** [comment]
Thank you so much for testing the app and reporting problems, that's very helpful for me! I'll look into fixing them tomorrow.

**Comment by rene-coty** [comment]
Still doesn't seem to work :/…

**Comment by david-swift** [comment]
Strange, it works for me.

[Screencast from 2024-03-09 17-30-09.webm](https://github.com/david-swift/Memorize/assets/106754840/23657f82-3051-4267-9b88-dd5fe83b5875)

How did you install the app? Via Flathub, did you build the Flatpak yourself, or are you using `swift run`? It should work in all cases, but (I think) the XDG data directory differs.

Can you maybe take a look at what happens with the file `~/.var/app/io.github.david_swift.Flashcards/data/io.github.david_swift.Flashcards/width.json` (see video)? Are there problems writing the data to the file, or does the "default default size" override the default size in the file when starting the app?

If there's a problem storing the data: Do you also have problems with the flashcard sets, are they loaded incorrectly after restarting the app?

**Comment by rene-coty** [comment]
Ah I see: custom resizing is OK, but the 'maximized' state of the window isn't retained
When I resize the window myself, the new dimensions will immediatly appear in `width.json` and `height.json`. Maximizing the window using the top right button doesn't to affect them though…

**Comment by david-swift** [comment]
Yes, this is a separate thing. I'll add it as well.

**Comment by david-swift** [comment]
It now remembers whether it is maximized as well (73ed48b).
